-  name: mongodb
   hosts: mongodb
   become: yes
   tasks:
     - name: copy mongodb.repo
       ansible.builtin.copy:
          src: mongodb.repo
          dest: /etc/yum.repos.d/mongodb.repo

     -  name: install mongodb.repo
        ansible.builtin.package:
           name: mongodb-org
           state: present

     -  name: enable and started mongodb
        ansible.builtin.systemd_service:
           name: mongod
           state: started
           enabled: yes

     - name: modifyed remote connection
       ansible.builtin.replace:
           path: /etc/mongod.conf
           regexp: '127.0.0.1'
           replace: '0.0.0.0'

     - name: enable and started mongodb
       ansible.builtin.systemd_service:
           name: mongod
           state: restarted

     -  name: install mongodb.repo
        ansible.builtin.package:
           name: mongodb-org
           state: present

     -  name: get the categories count
        ansible.builtin.command:  mongo --host mongodb.2512raju.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
        register: product_count

     - name: load catalogue data
       ansible.builtin.shell: mongo --host mongodb.2512raju.online < /app/schema/catalogue.js
       when: product_count.stdout == "0"

     - name: start and enable catalogue
       ansible.builtin.service:
          name: catalogue
          state: restarted
          enabled: yes

     

        